---
- hosts: sprayer-bot
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - euro2.base-setup

  tasks:
  - name: add custom ppa
    apt_repository:
      repo: "{{ item }}"
    with_items:
      - 'ppa:nginx/stable'
      - 'ppa:webupd8team/java'

  # java, nginx
  - name: accept oracle java license
    debconf:
      name: 'oracle-java8-installer'
      question: 'shared/accepted-oracle-license-v1-1'
      value: 'true'
      vtype: 'select'

  - name: install extended packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - letsencrypt
      - nginx-full
      - oracle-java8-installer

  ## nginx
  - name: configure nginx
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: remove default index.html
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob:
      - "/var/www/html/*"

  - name: check if dhparam file is present
    stat:
      path: /etc/nginx/dhparam.pem
    register: dhparam_file

  - name: generate dhparam if not present
    command:
      'openssl dhparam -out /etc/nginx/dhparam.pem 2048'
    when: dhparam_file.stat.exists == False

  - name: configure sprayer-bot.euro2.ee nginx server
    copy:
      src: nginx_sprayer-bot.conf
      dest: /etc/nginx/conf.d/sprayer-bot.conf

  # sprayer bot
  - name: create sprayer bot directory
    file:
      state: directory
      path: /opt/sprayer-bot/builds
      owner: sprayer-bot
      group: sprayer-bot

  - name: create directory for user systemd ini files
    file:
      state: directory
      path: /home/sprayer-bot/.config/systemd/user/
      owner: sprayer-bot
      group: sprayer-bot

  - name: create wallet server user systemd ini file
    copy:
      src: systemd/sprayer-bot.service
      dest: /home/sprayer-bot/.config/systemd/user/sprayer-bot.service
      owner: sprayer-bot
      group: sprayer-bot

  - name: add environment variable to .profile in order to get systemd --user working
    lineinfile:
      path: /home/sprayer-bot/.profile
      line: 'export XDG_RUNTIME_DIR=/run/user/`id -u`'
      state: present

  - name: add sprayer-bot user to journal group in order to read logs
    user:
      name: sprayer-bot
      append: yes
      groups: systemd-journal

  - name: get latest newrelic agent jar
    unarchive:
      src: files/newrelic-java-4.0.0.zip
      dest: /opt/sprayer-bot/
      owner: sprayer-bot
      group: sprayer-bot
...
