---
#TODO make account-mapper accept http connections, currently only ajp is accepted
- hosts: id
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - euro2.base-setup

  tasks:
  - name: add custom ppa
    apt_repository:
      repo: "{{ item }}"
    with_items:
      - 'ppa:nginx/stable'
      - 'ppa:webupd8team/java'

  - name: set licence selected
    shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

  - name: set licence seen
    shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections

  - name: install extended packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - letsencrypt
      - ldapscripts
      - nginx-full
      - oracle-java8-installer

  ## nginx
  - name: configure nginx
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

  - name: remove default index.html
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob:
      - "/var/www/html/*"

  - name: check if dhparam file is present
    stat:
      path: /etc/nginx/dhparam.pem
    register: dhparam_file

  - name: generate dhparam if not present
    command:
      'openssl dhparam -out /etc/nginx/dhparam.pem 2048'
    when: dhparam_file.stat.exists == False

  - name: create certificate directory
    file:
      dest: /etc/nginx/certificates
      state: directory

  - name: copy bundled id card root certificates
    copy:
      src: ca_estid.bundle.crt
      dest: /etc/nginx/certificates/id.bundle.crt

  - name: configure id.euro2.ee nginx server
    copy:
      src: nginx_id.conf
      dest: /etc/nginx/conf.d/id.conf
    notify: restart nginx

  # account identity mapper
  - name: create account identity mapper directory
    file:
      state: directory
      path: /opt/account-identity/builds
      owner: account-identity
      group: account-identity

  - name: create directory for user systemd ini files
    file:
      state: directory
      path: /home/account-identity/.config/systemd/user/

  - name: create wallet server user systemd ini file
    copy:
      src: systemd/account-identity.service
      dest: /home/account-identity/.config/systemd/user/account-identity.service
      owner: account-identity
      group: account-identity

  - name: add environment variable to .profile in order to get systemd --user working
    lineinfile:
      path: /home/account-identity/.profile
      line: 'export XDG_RUNTIME_DIR=/run/user/`id -u`'
      state: present

  - name: add account-identity user to journal group in order to read logs
    user:
      name: account-identity
      append: yes
      groups: systemd-journal

  - name: get latest newrelic agent jar
    unarchive:
      src: files/newrelic-java-4.0.0.zip
      dest: /opt/account-identity/

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
...
