---
- hosts: "{{ target }}"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: reboot
      command: /sbin/reboot

    - name: Wait for the server to finish rebooting
      sudo: no
      local_action:
        wait_for:
          host: "{{ inventory_hostname }}"
          state: started
          timeout: 300
